name: Node.js CI [Unit tests]

on:
  pull_request:
    branches: [ main ]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      USE_PROFILE: true
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build --if-present
      - run: npm test
  check_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Packer
        run: sudo apt-get update && sudo apt-get install -y packer
      - name: Check Packer file format
        run: |
          if ! packer fmt -check packer; then
            echo "Packer format is not correct. Please run 'packer fmt' to fix the issue."
            exit 1
          fi
      - name: Check Packer file valid
        run: |
          packer init packer
          if ! packer validate packer; then
            echo "Packer files are not valid."
            exit 1
          fi