name: Packer Build

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 19.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build --if-present
      - run: npm test

  packer-build:
    name: Packer Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PKR_VAR_POSTGRES_USER: ${{ secrets.DB_USER }}
      PKR_VAR_POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
      PKR_VAR_POSTGRES_HOST: ${{ secrets.DB_HOST }}
      PKR_VAR_POSTGRES_PORT: ${{ secrets.DB_PORT }}
      PKR_VAR_POSTGRES_DB: ${{ secrets.DB_DATABASE }}
    if: github.event.pull_request.merged == true
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Packer
      run: sudo apt-get update && sudo apt-get install -y packer
    - name: Initialize packer
      run: packer init packer
    - name: Build Packer image
      run: packer build packer/ec2.pkr.hcl
      